version: '3.8'
services:
  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn main:app --host ${APP_HOST} --port ${APP_PORT} --reload
    depends_on:
      - redis

  celery:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    command: celery -A app.tasks.celery_tasks worker --loglevel=${LOG_LEVEL}
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

volumes:
  redis_data: